# Generated by Django 5.2 on 2025-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('comprime', 'Comprimé'), ('sirop', 'Sirop'), ('gelule', 'Gélule'), ('injection', 'Injection'), ('pommade', 'Pommade'), ('collyre', 'Collyre'), ('autre', 'Autre')], default='comprime', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('active_ingredient', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
