# Generated by Django 5.2 on 2025-12-05 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_doses', models.IntegerField(default=0)),
                ('remaining_doses', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'En cours'), ('completed', 'Terminé'), ('stopped', 'Arrêté'), ('overdue', 'En retard')], default='active', max_length=20)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('next_dose_time', models.TimeField(blank=True, null=True)),
                ('last_taken_at', models.DateTimeField(blank=True, null=True)),
                ('dose_times', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_medications', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name_plural': 'Médicaments patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('taken', models.BooleanField(default=False)),
                ('overdue', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='medications.patientmedication')),
            ],
            options={
                'verbose_name_plural': 'Prises de médicaments',
                'ordering': ['scheduled_time'],
            },
        ),
    ]
