# Generated by Django 5.2 on 2025-12-05 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('consultation', 'Consultation'), ('examen', 'Examen'), ('vaccination', 'Vaccination'), ('urgence', 'Urgence'), ('hospitalisation', 'Hospitalisation'), ('chirurgie', 'Chirurgie'), ('autre', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='consultations.consultation')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_history_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history_entries', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name_plural': "Entrées d'historique médical",
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_documents/')),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_history.medicalhistoryentry')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('à_jour', 'À jour'), ('bientôt_due', 'Bientôt due'), ('en_retard', 'En retard')], default='à_jour', max_length=20)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccinations', to=settings.AUTH_USER_MODEL)),
                ('history_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_record', to='medical_history.medicalhistoryentry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-date_administered'],
            },
        ),
    ]
